---
- name: copy {{app_name}} app
  copy: src={{app_name}} dest={{dest_path}} owner=root group=root mode=0755

- name: npm install
  npm: path={{app_path}}

- name: make sure nodejs service is not already running to avoid port conjuction
  shell: "ps -ef | grep bamboo | grep -v grep"
  become: yes
  ignore_errors: True
  register: is_app_running
- debug: var=is_app_running


- name: kill if running  
  shell: "pkill nodejs"
  when: is_app_running.stdout.find('bamboo') != -1

- name: run the {{app_name}} application
  shell: "nohup nodejs {{app_path}}/{{app_vers}}.js >/dev/null 2>&1 &"
  
